fix thread_pool_executor in shutdown situation
David-Haim/concurrencpp pull request #119
Opened 2023-03-26 06:35 UTC by Trafo

In case a shutdown exception will be thrown, it was not handled within the threads. In case that happens, we need to catch it, because it can be expected, otherwise, the program terminates.

Where I am more insecure is the `worker_thread_executor`. Not sure about what `m_private_atomic_abort` is doing here, but it was never set to true before, which causes the executor will not really be shut down. In case it will be set, it shutdowns as expected, and I don't see any side effects.

This is a follow-up from reported issue #118.

2023-04-05 20:53 UTC, David-Haim commented
@Trafo what's up?

2023-04-06 06:18 UTC, Trafo commented
@David-Haim Sorry context for me is missing. Is something missing that I need to provide?

2023-04-06 09:03 UTC, David-Haim requested changes

2023-04-06 09:03 UTC, David-Haim commented on source/executors/thread_pool_executor.cpp
> +        try {
make `try/catch` around the `while(true)` , not the way around

```cpp
try{
  while(true){
      ..
   }
 } catch(...){

}
```

2023-04-06 09:03 UTC, David-Haim commented on source/executors/thread_pool_executor.cpp
> +            m_idle = true;
add `std::unique_lock<std::mutex> lock(m_lock);` before, `m_idle` is a shared variable across threads.

2023-04-06 09:04 UTC, David-Haim commented
Sorry, my mistake. I added 2 comments about the code, but did not submit them as a review. Can you see them now?

2023-04-06 10:28 UTC, David-Haim commented
Great!
Once I merge it, can I close https://github.com/David-Haim/concurrencpp/issues/118 , or is there anything else?

2023-04-06 11:48 UTC, Trafo commented
Yes, you can close. Again, thx for your work. Without this lib, I don't know what I should do in the C++ cosmos. :)

2023-04-06 11:50 UTC, merged